#!/bin/bash

torrents_dir=~/.config/transmission/torrents

lists=(
    https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt
    https://raw.githubusercontent.com/zcq100/transmission-trackers/master/tracker_ipv6.txt
)

trackers=(
    http://1337.abcvg.info:80/announce
    http://glotorrents.pw:80/announce
    http://open.acgnxtracker.com/announce
    http://opentracker.i2p.rocks:6969/announce
    http://share.camoe.cn:8080/announce
    http://torrent-tracker.ru/announce.php
    http://tracker.bt4g.com:2095/announce
    http://tracker.btzoo.eu:80/announce
    http://tracker.files.fm:6969/announce
    http://tracker.gbitt.info:80/announce
    http://tracker.kamigami.org:2710/announce
    http://tracker.moeking.me:6969/announce
    http://tracker.skyts.net:6969/announce
    http://tracker1.itzmx.com:8080/announce
    http://tracker2.dler.org:80/announce
    http://tracker3.itzmx.com:6961/announce
    http://vps02.net.orel.ru:80/announce
    https://1337.abcvg.info:443/announce
    https://tracker.gbitt.info:443/announce
    https://tracker.nitrix.me:443/announce
    https://tracker.sloppyta.co:443/announce
    https://tracker.tamersunion.org:443/announce 
    udp://9.rarbg.com:2780/announce
    udp://9.rarbg.me:2900/announce
    udp://exodus.desync.com:6969/announce
    udp://ipv4.tracker.harry.lu:80/announce
    udp://open.stealth.si:80/announce
    udp://retracker.lanta-net.ru:2710/announce
    udp://tracker.cyberia.is:6969/announce
    udp://tracker.ds.is:6969/announce
    udp://tracker.internetwarriors.net:1337/announce
    udp://tracker.moeking.me:6969/announce
    udp://tracker.tiny-vps.com:6969/announce
    udp://tracker.torrent.eu.org:451
    udp://tracker.torrent.eu.org:451/announce
)

for list in ${lists[@]}; do
    trackers+=$(curl $list)
done

trackers=$(echo $trackers | xargs printf -- " -a %s")
list_size=$(echo $trackers | wc -l)

process_torrent() {
   transmission-show -a $1 | head -n2 >&2
   echo $trackers | xargs -n2 transmission-edit $1 1> /dev/null
}

if [ -z $1 ]; then
    files=$torrents_dir/*
    torrents_count=$(ls $torrents_dir | wc -l)
else
    files=$*
    torrents_count=$#
fi

for torrent in $files; do
    process_torrent $torrent
    echo # this line drives progressbar
done | pv -l -s $torrents_count > /dev/null

